### ISSUE TITLE
Server HA - stale topology entry on fdb on server ip change

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#846] opened 2023-10-31 17:34 UTC
## Bug Report
We have been trying to increase server replica count according to [HA Support](https://github.com/ByConity/ByConity/blob/ad2ad4677bf2793ffadf98fbcf33896fe8240202/doc/ha_support.md) doc. 
### Briefly describe the bug
We were doing some stress testing and this caused server node to oom and reschedule. After this server got assigned another IP. Daemon manager logs were showing unreachable server address with the old ip. We had to manually clean "byconity_SERVERS_TOPOLOGY" from foundation db to refresh the topology entry for daemon manager and servers as well. 
### The result you expected
It should either TTL out after a while or refresh itself during restart instead of getting stuck with the stale entry. 
### How to Reproduce
Just drain the node for a server pod and watch it schedule to another. Check daemon manager logs. 
### Version
master branch

**Comment by dmthuc** [comment] 2023-11-01 02:25
Hi ozcelgozde , thank you for reporting the bug. This is must because server topology failed to update by the leader server. We will look at it. cc @Andygogo15

**Comment by dmthuc** [comment] 2023-11-01 13:00
Hi @ozcelgozde , i tried to rescheduled the server pod to a different ip by change the number of replicas but we couldn't reproduce the issue. The topology is updated after a while after the server pod is up with a new ip. I wonder if could you send us the log

**Comment by dmthuc** [comment] 2023-11-02 02:22
Hi @lazywei, thank you for your info. It is really helpful. May i know what is the timezone you config for byconity? Or what is the timezone of the machine?

**Comment by dmthuc** [comment] 2023-11-02 02:28
It seems this issue is caused by TSO timestamp is lag behind the realtime and the topology expiration time

**Comment by dmthuc** [comment] 2023-11-02 02:31
Hi @lazywei , may i know the memory allocation you give to the TSO pod?

**Comment by ozcelgozde** [comment] 2023-11-02 13:06
But I noticed the time we get from TSO was lagging by 2 days. On Tuesday it was returning Sunday

**Comment by dmthuc** [comment] 2023-11-03 02:06
> But I noticed the time we get from TSO was lagging by 2 days. On Tuesday it was returning Sunday

Hi ozcelgozde, we have notice that is the issue. The issue is the physical part of timestamp from TSO is not increase because the thread is hang. We will fix it

**Comment by dmthuc** [comment] 2023-11-09 02:23
Hi @ozcelgozde , the fix has been merged into `master` branch

**Comment by ozcelgozde** [comment] 2023-11-09 09:28
Thanks we will try it out!

**Comment by dmthuc** [comment] 2023-11-10 10:47
Hi @ozcelgozde , actually we just found a bug in the new code. We will fix it soon and notice you again.

**Comment by dmthuc** [comment] 2023-11-14 03:34
Hi @ozcelgozde , the fix has been merged.

**Comment by dmthuc** [comment] 2023-11-20 02:49
If there is no more comments then I will close this issue. Please feel free to reopen or create new issue if you encounter any issues

**Closed by dmthuc** 2023-11-20 02:49 UTC
Labels: bug, P1
