### ISSUE TITLE
Under high concurrency, errors are reported： already exists SQLSTATE: 22000.: While executing Remote SQLSTATE: 22000. Stack trace

### ISSUE THREAD

**Issue by ThorManager** [ByConity/ByConity#1052] opened 2024-01-15 03:04 UTC
During the pressure testing process, we found that occasionally a problem was triggered when the QPS exceeded 30000:

![image](https://github.com/ByConity/ByConity/assets/96821352/736b6028-264f-4747-ae8e-dcffe01cdef4)
And SQL execution exceeds 8 seconds

**Comment by ThorManager** [comment] 2024-01-15 03:39
Supplement tso 
[tso.err.log](https://github.com/ByConity/ByConity/files/13934585/tso.err.log)

**Comment by wordhardqi** [comment] 2024-01-15 04:08
@yuanzhubi  tso cored. could u take a look?
2024.01.04 19:08:51.933435 [ 17207 ] {} <Error> StorageElector: Unknown format for election storage, content in kv
2024.01.04 19:08:52.934451 [ 17207 ] {} <Error> StorageElector: Unknown format for election storage, content in kv
2024.01.04 19:08:53.935394 [ 17207 ] {} <Error> StorageElector: Unknown format for election storage, content in kv
2024.01.04 19:08:54.936333 [ 17207 ] {} <Error> StorageElector: Unknown format for election storage, content in kv
2024.01.04 19:09:05.936971 [ 17207 ] {} <Fatal> StorageElector: We lost the election key result unexpectedly!
2024.01.04 19:09:05.937124 [ 17095 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm 1.0.0.0, build id: F6DC24C4C4DE6FD0) (from thread 17207) Terminate called without an active exception
2024.01.04 19:09:05.937342 [ 17501 ] {} <Fatal> BaseDaemon: ########################################
2024.01.04 19:09:05.937371 [ 17501 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: F6DC24C4C4DE6FD0) (from thread 17207) (no query) Received signal Aborted (6)
2024.01.04 19:09:05.937381 [ 17501 ] {} <Fatal> BaseDaemon: 
2024.01.04 19:09:05.937399 [ 17501 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fc34a7caacf 0x7fc34a79dea5 0x1a13eaba 0x1e97b968 0x1e97b8d5 0x1a005d54 0x1a006840 0xd5ac13f 0xd5b041a 0x7fc34c7f81ca 0x7fc34a7b5e73
2024.01.04 19:09:05.937448 [ 17501 ] {} <Fatal> BaseDaemon: 3. __GI_raise @ 0x4eacf in /usr/lib64/libc-2.28.so
2024.01.04 19:09:05.937456 [ 17501 ] {} <Fatal> BaseDaemon: 4. abort @ 0x21ea5 in /usr/lib64/libc-2.28.so
2024.01.04 19:09:05.946790 [ 17501 ] {} <Fatal> BaseDaemon: 5. terminate_handler() @ 0x1a13eaba in /usr/bin/clickhouse
2024.01.04 19:09:05.955888 [ 17501 ] {} <Fatal> BaseDaemon: 6. std::__terminate(void (*)()) @ 0x1e97b968 in /usr/bin/clickhouse
2024.01.04 19:09:05.965111 [ 17501 ] {} <Fatal> BaseDaemon: 7. std::terminate() @ 0x1e97b8d5 in /usr/bin/clickhouse
2024.01.04 19:09:05.973686 [ 17501 ] {} <Fatal> BaseDaemon: 8. DB::StorageElector::doFollowerCheck() @ 0x1a005d54 in /usr/bin/clickhouse
2024.01.04 19:09:05.982291 [ 17501 ] {} <Fatal> BaseDaemon: 9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::StorageElector::start()::$_0>(DB::StorageElector::start()::$_0&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x1a006840 in /usr/bin/clickhouse
2024.01.04 19:09:05.990874 [ 17501 ] {} <Fatal> BaseDaemon: 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd5ac13f in /usr/bin/clickhouse
2024.01.04 19:09:05.999467 [ 17501 ] {} <Fatal> BaseDaemon: 11. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xd5b041a in /usr/bin/clickhouse
2024.01.04 19:09:05.999493 [ 17501 ] {} <Fatal> BaseDaemon: 12. start_thread @ 0x81ca in /usr/lib64/libpthread-2.28.so
2024.01.04 19:09:05.999502 [ 17501 ] {} <Fatal> BaseDaemon: 13. clone @ 0x39e73 in /usr/lib64/libc-2.28.so
2024.01.04 19:09:06.139176 [ 17501 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: E2645FAE481246809AE7EE41413B48CD. There is no information about the reference checksum.
2024.01.05 16:49:29.586396 [ 18311 ] {} <Warning> StorageElector: It is updated successfully on remote but expired on local: address {

**Comment by yuanzhubi** [comment] 2024-01-15 05:21
Have we do some fdb clean command offline? The log shows the election key used to be removed. @ThorManager

**Comment by yuanzhubi** [comment] 2024-01-22 07:00
https://github.com/ByConity/ByConity/issues/1052 I think these issues are related, maybe the same cause.  TSO is confirmed not the cause.

**Comment by dmthuc** [comment] 2024-02-05 07:23
This is fixed in version 0.3.2 by PR #1114 https://github.com/ByConity/ByConity/pull/1114

**Closed** 2024-02-26 06:43 UTC
Labels: bug, resolved, P1
