### ISSUE TITLE
It is failed to query CnchMergeTree from the remote object disk because of the part_id of part is zero. 

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#326] opened 2023-06-06 08:09 UTC
Hello, all.
In my ByConity system, CnchMergeTree data is stored on remote object storage. After data is imported, data can be queried from ByConity.
However, occasionally querying data fails. I have not find a pattern of reappearance.
The part_id of the failed part is zero, so it is failed to query from server. But why the part_id of part save to zero?

Briefly describe the bug
It is failed to query from server, this is error log:

```
Code: 499. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: DB::Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra: SQLSTATE: HY000.: While executing Remote SQLSTATE: HY000.
```

And we can find these failed log from default-worker:
```
AWSClient[121] : Make request to: http://{endpoint}/{bucket}/{path}/{table_uuid}/00000000-0000-0000-0000-000000000000/data
AWSClient[104] : Request returned error. Attempting to generate appropriate error codes from response
AWSClient[104] : HTTP response code: 404
Resolved remote host IP address:
Request ID:
Exception name:
Error message: No response body.
12 response headers:
connection : close
content-length : 0
content-type :
date : xxxxxxx
server : xxxxxxxxx
x-amz-error-code : NoSuchKey
x-amz-error-detail-key : {path}/{table_uuid}/00000000-0000-0000-0000-000000000000/data
x-amz-error-message : The specified key does not exist.
```

This is stack info:
```
CnchWorkerService[195] : virtual void DB::CnchWorkerServiceImpl::sendQueryDataParts(google::protobuf::RpcController *, const Protos::SendDataPartsReq *, Protos::SendDataPartsResp *, google::protobuf::Closure *): Code: 499, e.displayText() = DB::S3::S3Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra: SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int) @ 0x1840f4b2 in /opt/byconity/byconity/bin/clickhouse
DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0xac43120 in /opt/byconity/byconity/bin/clickhouse
DB::S3::S3Exception::S3Exception(Aws::S3::S3Error const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0x12d79b97 in /opt/byconity/byconity/bin/clickhouse
DB::S3::S3Util::headObject(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) const @ 0x12d7f020 in /opt/byconity/byconity/bin/clickhouse
DB::S3::S3Util::getObjectSize(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) const @ 0x12d7eb43 in /opt/byconity/byconity/bin/clickhouse
DB::DiskByteS3::getFileSize(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) const @ 0x1361d5e6 in /opt/byconity/byconity/bin/clickhouse
DB::MergeTreeDataPartCNCH::loadPartDataFooter() const @ 0x145013fc in /opt/byconity/byconity/bin/clickhouse
DB::MergeTreeDataPartCNCH::loadChecksums(bool) @ 0x14506b9e in /opt/byconity/byconity/bin/clickhouse
DB::IMergeTreeDataPart::getChecksums() const @ 0x1442eeea in /opt/byconity/byconity/bin/clickhouse
DB::MergeTreeDataPartCNCH::loadColumnsChecksumsIndexes(bool, bool) @ 0x14500732 in /opt/byconity/byconity/bin/clickhouse
void std::__1::__function::__policy_invoker<void (std::__1::shared_ptrDB::IMergeTreeDataPart&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeCloudData::loadDataPartsInParallel(std::__1::vector<std::__1::shared_ptrDB::IMergeTreeDataPart, std::__1::allocator<std::__1::shared_ptrDB::IMergeTreeDataPart > >&)::$_0, void (std::__1::shared_ptrDB::IMergeTreeDataPart&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptrDB::IMergeTreeDataPart&) @ 0x14478513 in /opt/byconity/byconity/bin/clickhouse
ThreadPoolImpl::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xac7e0cf in /opt/byconity/byconity/bin/clickhouse
ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()>(void&&, void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xac7fe6c in /opt/byconity/byconity/bin/clickhouse
ThreadPoolImplstd::__1::thread::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xac7abc5 in /opt/byconity/byconity/bin/clickhouse
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ThreadPoolImplstd::__1::thread::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()> >(void*) @ 0xac7f0da in /opt/byconity/byconity/bin/clickhouse
? @ 0x8f3b in /usr/lib64/libpthread-2.28.so
clone @ 0xf8840 in /usr/lib64/libc-2.28.so
After I restart all processes of ByConity, I fase the same problem.
```

The part_id of this part is zero. ClickHouse-server query part metadata from KV store, the part_id of this part is zero "00000000-0000-0000-0000-000000000000".

Version
0.1.1.1

Does any one face the sampe problem?

**Comment by Adora627** [comment] 2023-07-18 02:52
@zhaojintaozhao hi we will close this issue since it has been a while with no clue and cannot reproduce for over a week.

**Closed by Adora627** 2023-07-18 02:52 UTC
Labels: bug, can not reproduce
