### ISSUE TITLE
Version 0.2.2 bug: Optimizer bug on `Array` data type (2): ARRAY JOIN could crash the server

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#963] opened 2023-12-14 08:12 UTC
**ByConity Version: 0.2.2
Workers in cluster: 2 default worker + 2 write worker**

**Open the optimizer:**
```
CREATE TABLE test.array1
(
    `date` Date DEFAULT today(),
    `id` UInt32 DEFAULT rand(),
    `array` Array(UInt8) DEFAULT [0, 1, 2],
    `struct.k` Array(UInt8) DEFAULT [0, 1, 2],
    `struct.v` Array(UInt8) ALIAS array
)
ENGINE = CnchMergeTree
PARTITION BY toYYYYMM(date)
ORDER BY id
SETTINGS index_granularity = 1, storage_policy = 'bytes3'

Ok.

0 rows in set. Elapsed: 0.019 sec. 


INSERT INTO test.array1 (id) VALUES

Ok.

1 rows in set. Elapsed: 0.138 sec. 


SELECT
    struct.k,
    struct.v
FROM test.array2
ARRAY JOIN struct

2023.12.13 15:04:16.674529 [ 1852972 ] <Fatal> BaseDaemon: ########################################
 2023.12.13 15:04:16.674656 [ 1852972 ] <Fatal> BaseDaemon: (version 21.8.7.1 scm 1.0.0.0, build id: CB1EA4710306330A99A0CE09E85911E092D23D89) (from thread 1849644) (query_id: 61553151-6ff5-4d5f-85b9-c700e54e4d6f) Received signal Segmentation fault (11)
 2023.12.13 15:04:16.674707 [ 1852972 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
 2023.12.13 15:04:16.674757 [ 1852972 ] <Fatal> BaseDaemon: Stack trace: 0x18cf4e3e 0x18cf4aca 0x18cf3a12 0x18cf2126 0x18cf204f 0x17e1edd0 0x17e20765 0x17e23a63 0x1807ea0e 0x1807a83b 0x18a90a74 0x18a9e73c 0x1d3d98ac 0x1d3d9d45 0x1d4c5fc7 0x1d4c386c 0x7f10f5531f4b 0x7f10f405174f
 2023.12.13 15:04:16.691949 [ 1852972 ] <Fatal> BaseDaemon: 3. DB::QueryAnalyzerVisitor::analyzeFrom(DB::ASTTablesInSelectQuery&, DB::ASTSelectQuery&) @ 0x18cf4e3e in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.708996 [ 1852972 ] <Fatal> BaseDaemon: 4. DB::QueryAnalyzerVisitor::visitASTSelectQuery(std::__1::shared_ptr<DB::IAST>&, DB::Void const&) @ 0x18cf4aca in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.725905 [ 1852972 ] <Fatal> BaseDaemon: 5. DB::QueryAnalyzerVisitor::analyzeSetOperation(std::__1::shared_ptr<DB::IAST>&, std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >&) @ 0x18cf3a12 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.744102 [ 1852972 ] <Fatal> BaseDaemon: 6. DB::QueryAnalyzer::analyze(std::__1::shared_ptr<DB::IAST>&, DB::Scope const*, std::__1::shared_ptr<DB::Context>, DB::Analysis&) @ 0x18cf2126 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.761118 [ 1852972 ] <Fatal> BaseDaemon: 7. DB::QueryAnalyzer::analyze(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>) @ 0x18cf204f in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.778005 [ 1852972 ] <Fatal> BaseDaemon: 8. DB::InterpreterSelectQueryUseOptimizer::buildQueryPlan() @ 0x17e1edd0 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.795203 [ 1852972 ] <Fatal> BaseDaemon: 9. DB::InterpreterSelectQueryUseOptimizer::getPlanSegment() @ 0x17e20765 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.812178 [ 1852972 ] <Fatal> BaseDaemon: 10. DB::InterpreterSelectQueryUseOptimizer::execute() @ 0x17e23a63 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.829299 [ 1852972 ] <Fatal> BaseDaemon: 11. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x1807ea0e in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.846265 [ 1852972 ] <Fatal> BaseDaemon: 12. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1807a83b in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.863208 [ 1852972 ] <Fatal> BaseDaemon: 13. DB::TCPHandler::runImpl() @ 0x18a90a74 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.880119 [ 1852972 ] <Fatal> BaseDaemon: 14. DB::TCPHandler::run() @ 0x18a9e73c in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.896982 [ 1852972 ] <Fatal> BaseDaemon: 15. Poco::Net::TCPServerConnection::start() @ 0x1d3d98ac in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.919814 [ 1852972 ] <Fatal> BaseDaemon: 16. Poco::Net::TCPServerDispatcher::run() @ 0x1d3d9d45 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.942874 [ 1852972 ] <Fatal> BaseDaemon: 17. Poco::PooledThread::run() @ 0x1d4c5fc7 in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.959718 [ 1852972 ] <Fatal> BaseDaemon: 18. Poco::ThreadImpl::runnableEntry(void*) @ 0x1d4c386c in /xx/xxx/xxx/clickhouse
 2023.12.13 15:04:16.959803 [ 1852972 ] <Fatal> BaseDaemon: 19. ? @ 0x8f4b in /usr/lib64/libpthread-2.28.so
 2023.12.13 15:04:16.959848 [ 1852972 ] <Fatal> BaseDaemon: 20. __clone @ 0xf874f in /usr/lib64/libc-2.28.so
 2023.12.13 15:04:17.112941 [ 1852972 ] <Fatal> BaseDaemon: Calculated checksum of the binary: DEF63E68AF1628EB7107822C5CC09374. There is no information about the reference checksum.
Error on processing query 'select struct.k, struct.v from test.array1 array join struct;':
Code: 32, e.displayText() = DB::Exception: Attempt to read after eof: while receiving packet from xx.xxx.xxx.xxx:pppp SQLSTATE: 22000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1d465032 in /xx/xxx/xxx/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xcd75360 in /xx/xxx/xxx/clickhouse
2. DB::throwReadAfterEOF() @ 0xcd86343 in /xx/xxx/xxx/clickhouse
3. ? @ 0xcddb179 in /xx/xxx/xxx/clickhouse
4. DB::Connection::receivePacket() @ 0x189f47eb in /xx/xxx/xxx/clickhouse
5. DB::Client::receiveAndProcessPacket(bool) @ 0xced8d2c in /xx/xxx/xxx/clickhouse
6. DB::Client::receiveResult() @ 0xcedb0a7 in /xx/xxx/xxx/clickhouse
7. DB::Client::processOrdinaryQuery() @ 0xcece4c1 in /xx/xxx/xxx/clickhouse
8. DB::Client::processParsedSingleQuery(std::__1::optional<bool>) @ 0xcecccea in /xx/xxx/xxx/clickhouse
9. DB::Client::processMultiQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xcecb638 in /xx/xxx/xxx/clickhouse
10. DB::Client::processQueryText(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xcec1401 in /xx/xxx/xxx/clickhouse
11. DB::Client::mainImpl() @ 0xcebd8bb in /xx/xxx/xxx/clickhouse
12. DB::Client::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xceba599 in /xx/xxx/xxx/clickhouse
13. Poco::Util::Application::run() @ 0x1d3e8e8a in /xx/xxx/xxx/clickhouse
14. mainEntryClickHouseClient(int, char**) @ 0xceaf21e in /xx/xxx/xxx/clickhouse
15. main @ 0xcd6de98 in /xx/xxx/xxx/clickhouse
16. __libc_start_main @ 0x25c57 in /usr/lib64/libc-2.28.so
17. _start @ 0xcd6d6aa in /xx/xxx/xxx/clickhouse
 (version 21.8.7.1)
```

**Close the optimizer, and execute the same query:**
```
:) set enable_optimizer = 0;

SET enable_optimizer = 0

Ok.

0 rows in set. Elapsed: 0.001 sec. 

:) select struct.k, struct.v from test.array1 array join struct;

SELECT
    struct.k,
    struct.v
FROM test.aliases_test
ARRAY JOIN struct

┌─struct.k─┬─struct.v─┐
│        0 │        0 │
│        1 │        1 │
│        2 │        2 │
└──────────┴──────────┘

3 rows in set. Elapsed: 0.159 sec. 

```

**Comment by FluorineDog** [comment] 2023-12-14 12:27
Though throwing exception should be the expected behaviour since we haven't support nested type yet, it's still unacceptable to have core dumps so we will fix it ASAP.

**Comment by kevinthfang** [comment] 2024-01-16 02:52
should fixed in latest version

**Closed** 2024-01-23 03:37 UTC
Labels: bug, resolved, P1
