### ISSUE TITLE
commit failed because txn record has been changed by other transactions

### ISSUE THREAD

**Issue by xujinlong0314** [ByConity/ByConity#1790] opened 2024-07-31 10:07 UTC
irtual DB::TxnTimestamp DB::CnchServerTransaction::commitV2(): Code: 11003, e.displayText() = DB::Exception: Transaction 451521030125518850 commit failed because txn record has been changed by other transactions SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c412 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /usr/bin/clickhouse
2. DB::CnchServerTransaction::commit() @ 0x1fff3c19 in /usr/bin/clickhouse
3. DB::CnchServerTransaction::commitV2() @ 0x1fff086d in /usr/bin/clickhouse
4. DB::CloudMergeTreeBlockOutputStream::writeSuffixForInsert() @ 0x21db5dcd in /usr/bin/clickhouse
5. DB::CloudMergeTreeBlockOutputStream::writeSuffix() @ 0x21db5924 in /usr/bin/clickhouse
6. DB::PushingToViewsBlockOutputStream::writeSuffix() @ 0x2111ad86 in /usr/bin/clickhouse
7. DB::CountingBlockOutputStream::writeSuffix() @ 0x207b3ec3 in /usr/bin/clickhouse
8. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x222c189f in /usr/bin/clickhouse
9. DB::TCPHandler::runImpl() @ 0x222bbdac in /usr/bin/clickhouse
10. DB::TCPHandler::run() @ 0x222ca8fc in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x271b1b4c in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x271b202c in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x2729913a in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x27296cec in /usr/bin/clickhouse
15. start_thread @ 0x89c02 in /usr/lib64/libc.so.6
16. __GI___clone3 @ 0x10ec40 in /usr/lib64/libc.so.6
(url)
## Bug Report
Whether using orc to import or using clickhouse insert remote, this exception will occur after writing some data

### Version
0.4.2

[https://github.com/ByConity/ByConity/issues/1694](url)

**Comment by smmsmm1988** [comment] 2024-08-01 03:27
please refer to https://github.com/ByConity/ByConity/issues/1694
You can try modifying TXN_GC interval: 600000 -> 60000 in daemon manager config and have an observation.

**Comment by xujinlong0314** [comment] 2024-08-02 05:47
> please refer to #1694 You can try modifying TXN_GC interval: 600000 -> 60000 in daemon manager config and have an observation.请参考#1694 您可以尝试在守护进程管理器配置中修改 TXN_GC 间隔：600000 -> 60000 并进行观察。

no effect

**Comment by smmsmm1988** [comment] 2024-08-05 03:24
> > please refer to #1694 You can try modifying TXN_GC interval: 600000 -> 60000 in daemon manager config and have an observation.请参考#1694 您可以尝试在守护进程管理器配置中修改 TXN_GC 间隔：600000 -> 60000 并进行观察。
> 
> no effect

does the exception still occur now?

**Comment by fky2015** [comment] 2024-08-10 14:11
Can still produce at master branch:

![image](https://github.com/user-attachments/assets/37feab9f-b232-41dc-9812-6eef701c3651)

To reproduce:

insert into one table concurrently.

**Comment by smmsmm1988** [comment] 2024-08-12 02:41
> Can still produce at master branch:
> 
> ![image](https://private-user-images.githubusercontent.com/16451516/356816365-37feab9f-b232-41dc-9812-6eef701c3651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzA1MzgsIm5iZiI6MTcyMzQzMDIzOCwicGF0aCI6Ii8xNjQ1MTUxNi8zNTY4MTYzNjUtMzdmZWFiOWYtYjIzMi00MWRjLTk4MTItNmVlZjcwMWMzNjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAyMzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTc4Zjc4N2I5NmQwNjQ3N2NmZDljNGE2MTEzZWI2Y2M2NjZjZjkwMzFkMjI2OGU3YzAzN2YzZTgyZmJiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xqOtfnW0Ds4Fhqa-LFThoWyM3Ir6xhVgY-SRYN8Ze4M)
> 
> To reproduce:
> 
> insert into one table concurrently.

it is somewhat weird. Concurrently inserts of one table should have no impact on each other. Is the exception due to error of CAS operation in KV?

**Comment by fky2015** [comment] 2024-08-13 08:26
Already found the root cause of the bug.

It's because we're confusing the usage of hostname and IP when `service_discovery.mode = local`, and trying to compare them via `==`.

Will be fixed soon.

**Comment by fky2015** [comment] 2024-08-13 08:50
It's not a very orthodox way, but you can try set environment `MY_HOST_IP=<your host name>`.
e.g. `MY_HOST_IP=server-0` on server-0. (haven't tested)

---

If you could compile binary, you can also use this patch:

```diff
diff --git a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
index b3bd87a2c66..a63fc2322ee 100644
--- a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
+++ b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
@@ -1,11 +1,12 @@
 #include <ServiceDiscovery/ServiceDiscoveryLocal.h>
 
 #include <IO/ReadHelpers.h>
+#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
+#include <Poco/Util/AbstractConfiguration.h>
+#include <Common/DNSResolver.h>
 #include <Common/Exception.h>
 #include <Common/ProfileEvents.h>
 #include <Common/StringUtils/StringUtils.h>
-#include <Poco/Util/AbstractConfiguration.h>
-#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
 
 #include <sstream>
 #include <consul/discovery.h>
@@ -49,6 +50,20 @@ HostWithPortsVec ServiceDiscoveryLocal::lookup(const String & psm_name, Componen
             if (type == ComponentType::WORKER && !vw_name.empty() && ep.virtual_warehouse != vw_name)
                 continue;
 
+            // We need to resolve hostname to ip,
+            // because we will use ip to set `TransactionRecord`.
+            try
+            {
+                auto ip = DNSResolver::instance().resolveHost(ep.host).toString();
+                if (!ip.empty())
+                {
+                    ep.host = ip;
+                }
+            }
+            catch (...)
+            {
+            }
+
             HostWithPorts host_with_ports{ep.host};
             host_with_ports.id = ep.hostname;
             if (ep.ports.count("PORT0"))
```

**Comment by xujinlong0314** [comment] 2024-08-13 10:28
> It's not a very orthodox way, but you can try set environment `MY_HOST_IP=<your host name>`. e.g. `MY_HOST_IP=server-0` on server-0. (haven't tested)
> 
> If you could compile binary, you can also apply this patch:
> 
> ```diff
> diff --git a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> index b3bd87a2c66..a63fc2322ee 100644
> --- a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> +++ b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> @@ -1,11 +1,12 @@
>  #include <ServiceDiscovery/ServiceDiscoveryLocal.h>
>  
>  #include <IO/ReadHelpers.h>
> +#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
> +#include <Poco/Util/AbstractConfiguration.h>
> +#include <Common/DNSResolver.h>
>  #include <Common/Exception.h>
>  #include <Common/ProfileEvents.h>
>  #include <Common/StringUtils/StringUtils.h>
> -#include <Poco/Util/AbstractConfiguration.h>
> -#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
>  
>  #include <sstream>
>  #include <consul/discovery.h>
> @@ -49,6 +50,20 @@ HostWithPortsVec ServiceDiscoveryLocal::lookup(const String & psm_name, Componen
>              if (type == ComponentType::WORKER && !vw_name.empty() && ep.virtual_warehouse != vw_name)
>                  continue;
>  
> +            // We need to resolve hostname to ip,
> +            // because we will use ip to set `TransactionRecord`.
> +            try
> +            {
> +                auto ip = DNSResolver::instance().resolveHost(ep.host).toString();
> +                if (!ip.empty())
> +                {
> +                    ep.host = ip;
> +                }
> +            }
> +            catch (...)
> +            {
> +            }
> +
>              HostWithPorts host_with_ports{ep.host};
>              host_with_ports.id = ep.hostname;
>              if (ep.ports.count("PORT0"))
> ```

Thanks, I'll try it

**Comment by ixnzh** [comment] 2024-09-03 03:00
> > It's not a very orthodox way, but you can try set environment `MY_HOST_IP=<your host name>`. e.g. `MY_HOST_IP=server-0` on server-0. (haven't tested)
> > If you could compile binary, you can also apply this patch:
> > ```diff
> > diff --git a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> > index b3bd87a2c66..a63fc2322ee 100644
> > --- a/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> > +++ b/src/ServiceDiscovery/ServiceDiscoveryLocal.cpp
> > @@ -1,11 +1,12 @@
> >  #include <ServiceDiscovery/ServiceDiscoveryLocal.h>
> >  
> >  #include <IO/ReadHelpers.h>
> > +#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
> > +#include <Poco/Util/AbstractConfiguration.h>
> > +#include <Common/DNSResolver.h>
> >  #include <Common/Exception.h>
> >  #include <Common/ProfileEvents.h>
> >  #include <Common/StringUtils/StringUtils.h>
> > -#include <Poco/Util/AbstractConfiguration.h>
> > -#include <ServiceDiscovery/ServiceDiscoveryFactory.h>
> >  
> >  #include <sstream>
> >  #include <consul/discovery.h>
> > @@ -49,6 +50,20 @@ HostWithPortsVec ServiceDiscoveryLocal::lookup(const String & psm_name, Componen
> >              if (type == ComponentType::WORKER && !vw_name.empty() && ep.virtual_warehouse != vw_name)
> >                  continue;
> >  
> > +            // We need to resolve hostname to ip,
> > +            // because we will use ip to set `TransactionRecord`.
> > +            try
> > +            {
> > +                auto ip = DNSResolver::instance().resolveHost(ep.host).toString();
> > +                if (!ip.empty())
> > +                {
> > +                    ep.host = ip;
> > +                }
> > +            }
> > +            catch (...)
> > +            {
> > +            }
> > +
> >              HostWithPorts host_with_ports{ep.host};
> >              host_with_ports.id = ep.hostname;
> >              if (ep.ports.count("PORT0"))
> > ```
> 
> Thanks, I'll try it

Any other questions？

**Comment by smmsmm1988** [comment] 2024-09-11 03:22
This bug has been resolved and will appear in later versions. For old versions, one can apply the patch here to avoid such problem.

**Closed by smmsmm1988** 2024-09-11 03:22 UTC
Labels: bug, P1
