### ISSUE TITLE
 DB::Exception: Not found column in block

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#466] opened 2023-07-10 09:45 UTC
When i write data into ByConity, the byconity-server's error log show the error below all the time.

```
2023.07.10 17:37:35.031644 [ 117761 ] {} <Error> apm.middleware_dubbo_service_request_rt (b6707077-6451-4f45-928d-3e69e20776be)(PartGCThread): virtual void DB::CnchPartGCThread::runImpl(): Code: 10, e.displayText() = DB::Exception: Not found column _time in block: while executing 'INPUT : 0 -> _time Int64 : 0' SQLSTATE: 22000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xb70a564 in /opt/byconity/bin/clickhouse
3. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x144aed6a in /opt/byconity/bin/clickhouse
4. DB::ExpressionActions::execute(DB::Block&, bool) const @ 0x144af097 in /opt/byconity/bin/clickhouse
5. DB::CnchPartGCThread::tryMarkExpiredPartitions(DB::StorageCnchMergeTree&, std::__1::vector<std::__1::shared_ptr<DB::ServerDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::ServerDataPart const> > > const&) @ 0x143ea7f6 in /opt/byconity/bin/clickhouse
6. DB::CnchPartGCThread::clearOldPartsByPartition(std::__1::shared_ptr<DB::IStorage> const&, DB::StorageCnchMergeTree&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::TxnTimestamp) @ 0x143e7c40 in /opt/byconity/bin/clickhouse
7. DB::CnchPartGCThread::runImpl() @ 0x143e66cc in /opt/byconity/bin/clickhouse
8. DB::ICnchBGThread::run() @ 0x13c01671 in /opt/byconity/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13e2bede in /opt/byconity/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x13e2e287 in /opt/byconity/bin/clickhouse
11. ? @ 0x13e2e8f7 in /opt/byconity/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb69c67f in /opt/byconity/bin/clickhouse
13. ? @ 0xb6a095a in /opt/byconity/bin/clickhouse
14. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
15. __clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
```

table struct:
```
CREATE TABLE apm.middleware_dubbo_service_request_rt
(
    `_time` Int64 COMMENT 'null',
    `_app` LowCardinality(String) COMMENT 'null',
    `_ip` LowCardinality(String) COMMENT 'null',
    `_region` LowCardinality(String) COMMENT 'null',
    `_max` Float64 COMMENT 'null',
    `_mean` Float64 COMMENT 'null',
    `operation_name` LowCardinality(String) COMMENT 'null',
    `operation_side` LowCardinality(String) COMMENT 'null'
)
ENGINE = CnchMergeTree
PARTITION BY toDate(_time / 1000)
ORDER BY (_time, _app, _ip, _region, operation_name, operation_side)
TTL toDate(_time / 1000) + toIntervalDay(14)
SETTINGS index_granularity = 8192, storage_policy = 'cnch_default_hdfs'
```

And i found error throw by this file.
<img width="1031" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/5d53cff5-d4c3-422a-951e-15d938bcfdba">

But the write and read is still normal. Should i care about this error ?

byconity version: 0.1.0-GA

os version:
Linux version 4.14.105-19-0018 (root@VM_197_173_centos) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Thu Dec 3 09:59:51 CST 2020

**Comment by hustnn** [comment] 2023-07-10 13:09
Thanks for reporting, it maybe a bug, we will check. yes, the write and read are still working but the ttl may not work as expected, you can check it.

**Comment by xingcici** [comment] 2023-07-11 02:23
> Thanks for reporting, it maybe a bug, we will check. yes, the write and read are still working but the ttl may not work as expected, you can check it.

OK, i will also look into the problem.

**Comment by hustnn** [comment] 2023-07-11 03:52
hey, @xingcici can you try not use "_xx" as the column name? The "_" is a reserved keywaord for virtual column in ByConity such as "_part".

**Comment by xingcici** [comment] 2023-07-11 06:02
> hey, @xingcici can you try not use "_xx" as the column name? The "_" is a reserved keywaord for virtual column in ByConity such as "_part".

You mean the column should not start with "_" ?

**Comment by dmthuc** [comment] 2023-07-11 06:55
> > hey, @xingcici can you try not use "_xx" as the column name? The "_" is a reserved keywaord for virtual column in ByConity such as "_part".
> 
> You mean the column should not start with "_" ?

Yeah, could you try again to see if the issue still remain, the `_` prefix is reversed for virtual column

**Comment by xingcici** [comment] 2023-07-11 08:23
> > > hey, @xingcici can you try not use "_xx" as the column name? The "_" is a reserved keywaord for virtual column in ByConity such as "_part".
> > 
> > 
> > You mean the column should not start with "_" ?
> 
> Yeah, could you try again to see if the issue still remain, the `_` prefix is reversed for virtual column

- i create table without `_` and it's work fine .
- Is `_` not supported for all create table keywords or only not supported for TTL ? Such as `ORDER BY` and others .
- Will this issue be supported ？ Our APM metric table  are all contains the `_time` and TTL by it.

Thanks.

**Comment by xingcici** [comment] 2023-07-11 08:32
> > > hey, @xingcici can you try not use "_xx" as the column name? The "_" is a reserved keywaord for virtual column in ByConity such as "_part".
> > 
> > 
> > You mean the column should not start with "_" ?
> 
> Yeah, could you try again to see if the issue still remain, the `_` prefix is reversed for virtual column

It's still show the error.
```
2023.07.11 16:29:09.127125 [ 117831 ] {} <Error> apm.middleware_dubbo_service_request_rt (02221c62-44f7-466d-a449-8ab029541bc3)(PartGCThread): virtual void DB::CnchPartGCThread::runImpl(): Code: 10, e.displayText() = DB::Exception: Not found column time in block: while executing 'INPUT : 0 -> time Int64 : 0' SQLSTATE: 22000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xb70a564 in /opt/byconity/bin/clickhouse
3. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x144aed6a in /opt/byconity/bin/clickhouse
4. DB::ExpressionActions::execute(DB::Block&, bool) const @ 0x144af097 in /opt/byconity/bin/clickhouse
5. DB::CnchPartGCThread::tryMarkExpiredPartitions(DB::StorageCnchMergeTree&, std::__1::vector<std::__1::shared_ptr<DB::ServerDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::ServerDataPart const> > > const&) @ 0x143ea7f6 in /opt/byconity/bin/clickhouse
6. DB::CnchPartGCThread::clearOldPartsByPartition(std::__1::shared_ptr<DB::IStorage> const&, DB::StorageCnchMergeTree&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::TxnTimestamp) @ 0x143e7c40 in /opt/byconity/bin/clickhouse
7. DB::CnchPartGCThread::runImpl() @ 0x143e66cc in /opt/byconity/bin/clickhouse
8. DB::ICnchBGThread::run() @ 0x13c01671 in /opt/byconity/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13e2bede in /opt/byconity/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x13e2e287 in /opt/byconity/bin/clickhouse
11. ? @ 0x13e2e8f7 in /opt/byconity/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb69c67f in /opt/byconity/bin/clickhouse
13. ? @ 0xb6a095a in /opt/byconity/bin/clickhouse
14. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
15. __clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
```

```
CREATE TABLE apm.middleware_dubbo_service_request_rt
(
    `time` Int64 COMMENT 'null',
    `_app` LowCardinality(String) COMMENT 'null',
    `_ip` LowCardinality(String) COMMENT 'null',
    `_region` LowCardinality(String) COMMENT 'null',
    `_max` Float64 COMMENT 'null',
    `_mean` Float64 COMMENT 'null',
    `operation_name` LowCardinality(String) COMMENT 'null',
    `operation_side` LowCardinality(String) COMMENT 'null'
)
ENGINE = CnchMergeTree
PARTITION BY toDate(time / 1000)
ORDER BY (time, _app, _ip, _region, operation_name, operation_side)
TTL toDate(time / 1000) + toIntervalDay(14)
SETTINGS index_granularity = 8192, storage_policy = 'cnch_default_hdfs'
```


Should I remove all `_` or only TTL by column is fine ?

**Comment by dmthuc** [comment] 2023-07-11 08:33
Thank you for your check. Let us reproduce and fix this

**Comment by dmthuc** [comment] 2023-07-13 03:40
I've found the bug. This is not because the column start with `_`. We will fix it soon

**Comment by dmthuc** [comment] 2023-07-13 03:53
Hi @hustnn , this problem is fixed in cnch-ce-merge. It will be solved after code sync

**Comment by xingcici** [comment] 2023-07-18 02:24
Hi @dmthuc , when can this feature merge into master and release a version ? We will deploy By-Conity in prod env soon.
Thanks.

**Comment by dmthuc** [comment] 2023-07-18 02:39
Hi @hustnn , could you take a look at this case?

**Comment by dmthuc** [comment] 2023-07-18 03:37
Hi @xingcici , the code sync will take probably 2 weeks. It is ok. If it not then we will manually pick the fix first

**Comment by xingcici** [comment] 2023-07-18 05:37
> Hi @xingcici , the code sync will take probably 2 weeks. It is ok. If it not then we will manually pick the fix first

OK, Thanks.

**Comment by xingcici** [comment] 2023-07-18 05:50
> Hi @xingcici , the code sync will take probably 2 weeks. It is ok. If it not then we will manually pick the fix first

Hi, If i use current version for prod deploy now, and after the fix version release i upgrade the cluster. Will the ttl function work fine and clean the old data automatic ? Or do I have to do it manually after upgrade ? 
Do you have some suggestion ?

**Comment by dmthuc** [comment] 2023-07-18 05:53
Hi @xingcici , it will work fine. Or you can create table with out ttl now. And later alter table to add TTL

**Closed** 2023-07-20 03:05 UTC
Labels: bug, resolved
